# Generated by Django 5.2.4 on 2025-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes like S,M,L or 36,38,40', max_length=100),
        ),
    ]
